version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helenair
      POSTGRES_USER: isabella
      POSTGRES_PASSWORD: helenair
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
