version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: 
      context: ./frontend/helena-ir
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/helena-ir:/app
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helenair
      POSTGRES_USER: isabella
      POSTGRES_PASSWORD: helenair
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
      - ../csv:/backend/sql
volumes:
  pg_data: