version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/helena-ir
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helenair
      POSTGRES_USER: isabella
      POSTGRES_PASSWORD: helenair
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
