"""unique key pair constraint

Revision ID: 4697debfd8ae
Revises: 3db450659dfb
Create Date: 2024-02-13 11:48:32.907939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4697debfd8ae'
down_revision: Union[str, None] = '3db450659dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questionnaire_results_questionnaire_id', table_name='questionnaire_results')
    op.create_index(op.f('ix_questionnaire_results_questionnaire_id'), 'questionnaire_results', ['questionnaire_id'], unique=False)
    op.create_unique_constraint(None, 'questionnaire_results', ['questionnaire_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_results', type_='unique')
    op.drop_index(op.f('ix_questionnaire_results_questionnaire_id'), table_name='questionnaire_results')
    op.create_index('ix_questionnaire_results_questionnaire_id', 'questionnaire_results', ['questionnaire_id'], unique=True)
    # ### end Alembic commands ###
