"""Foreign key additions

Revision ID: 9d791a4b059c
Revises: d33a2d07bb84
Create Date: 2024-02-09 19:02:28.734781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d791a4b059c'
down_revision: Union[str, None] = 'd33a2d07bb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questionnaire_results_user_id', table_name='questionnaire_results')
    op.create_foreign_key(None, 'questionnaire_results', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_results', type_='foreignkey')
    op.create_index('ix_questionnaire_results_user_id', 'questionnaire_results', ['user_id'], unique=False)
    # ### end Alembic commands ###
