"""create user table

Revision ID: a7a781217a55
Revises: 
Create Date: 2023-12-27 16:02:38.399181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a781217a55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_table('body_fat_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_fat_classification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('underfat_min', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('underfat_max', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('normal_min', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('normal_max', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('overweight_min', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('overweight_max', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('obese_min', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('obese_max', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='body_fat_classification_pkey')
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
